### ISSUE TITLE
Box2 or Box3 or what?

### ISSUE THREAD

**Issue by xtrasmal** [box-project/box2#109]
Hello. I reallly want the box phar, but Im not sure where to get it. 
What happened to this project and what is happening to the box project?

Site is up for renewal and all the kherge/ etc naming is confusing.

**Comment by kherge** [comment]
- The version you want to use is Box 2.
- The `kherge/` namespace is where the project originally lived, until I moved everything into `box-project`.
- The project is stagnating because I'm so busy with work and life in general. Box 3 was my attempt at making a cleaner and more flexible version of Box.
