### ISSUE TITLE
Cant run box after installing through Composer

### ISSUE THREAD

**Issue by paishin** [box-project/box2#120]
I'm new to composer so excuse me if this is a very basic question.

I have installed box in my project locally but when running 'box' command I get 
"'box' is not recognized as an internal or external command,operable program or batch file."
which basically means file not found.

how can i fix this?

**Comment by kherge** [comment]
Hi @paishin!

Composer installs dependencies into a `vendor/` directory, which is found in the same location as the `composer.json` file.

To access commands made available by your dependencies, you will want to look in `vendor/bin/`. For Box, you would run `vendor/bin/box`.

I'll be closing this issue because it is not an issue with Box, but please feel free to ask more questions. I'll do what I can to help out!
