### ISSUE TITLE
Ignored dot files

### ISSUE THREAD

**Issue by ogizanagi** [box-project/box2#121]
Currently, dot files are ignored, due to the `symfony/finder` default behavior which is to ignore both vcs and dotfiles.

What about a configuration option in order to not ignore those files ? (`ignore-dot-files`, default `true` for BC reasons)

The only way for now is to add those files manually using the `files` configuration option.

**Comment by kherge** [comment]
I would classify this use case as advanced file inclusion, which is where using the [`finder` configuration setting](https://github.com/box-project/box2/blob/2.6.1/src/lib/KevinGH/Box/Command/Build.php#L242-L251) would be required. This setting can be used to alter Finder's default behavior, in addition to many other Finder-specific things. The `finder` setting is basically mapped to method calls on instances of the Finder class.

I'm leaning strongly towards not implementing something like `ignore-dot-files` because I would basically be re-implementing a dumbed down version of the Finder component. The `directories` setting is for a far simpler use case.

Does my view make sense, or am I being too much of a hardliner here?

EDIT: By the way, I'm really sorry for not seeing this response sooner. I never received a notification from GitHub about this issue being opened!

**Comment by ogizanagi** [comment]
No problem. I think it makes sense actually. I've probably overlooked at the `finder` configuration at the time.

I guess this issue can be closed :)

**Comment by kherge** [comment]
No biggy!
