### ISSUE TITLE
Consider adding an option to avoid comment stripping

### ISSUE THREAD

**Issue by schmittjoh** [box-project/box2#40]
At the moment, all comments are stripped by default. This introduces bugs in the compiled code if for example Doctrine annotations are removed.

I'd therefore suggest to make this an optional switch can be enabled/disabled, or not strip Doctrine annotations. The latter seems more complex though.

**Comment by digitalkaoz** [comment]
ran into the same problem, any news on that one?

**Comment by ghost** [comment]
The long term solution would be to create or modify the PHP [compactor class](https://github.com/herrera-io/php-box/wiki/CompactorInterface) to preserve annotations. I am planning on creating one for the 2.1 release.

For now, you can create and register a custom compactor class using a combination of the `compactors` and `bootstrap` settings.

> You can find information about configuration settings by running: `php box.phar build --help`

Another temporary solution, if your annotated files are all contained within one or more directories, would be to use one of the `*-bin` settings to load files as is:

**Example** `box.json`:

``` json
{
    "directories": ["src"],
    "directories-bin": ["src/annotated"]
}
```

The effects of the configuration are
1. Import and compact all source in `src`
2. Import as-is all source in `src/annotated`

> You will need to use the current commit for Box. I have made changes to the order in which Box imports files.

The consequence of using this solution is that
- the files imported using `directories-bin` will not be compacted
- will increase build time since the annotated files will actually be imported twice: once by `directories`, and then again by `directories-bin`

The second part might not even be a concern if its only a few files.

**Comment by schmittjoh** [comment]
Looks good. Thanks for the quick response!

**Comment by digitalkaoz** [comment]
worked like a charm...but the longterm solution to keep real annotations would be nice ;)

**Comment by ghost** [comment]
Sorry for the uber long wait, it's been crazy!

[Box 2.4.0](https://github.com/kherge/Box/releases/tag/2.4.0) should now officially support this.
