### ISSUE TITLE
Do you really need phpspec in require and not require-dev

### ISSUE THREAD

**Issue by lyrixx** [box-project/box2#48]
Because I want to require you lib. And when I do that, I got phpspec. So I add lot of dependencies.

**Comment by ghost** [comment]
The library in `require` is php **sec** lib (`phpseclib`), a "secure communications library".

I use that to generate private keys and extract public keys when the `openssl` extension is not installed.

The `phpspec` library is not used.

Also if you want to use the library, I suggest using `herrera-io/box` instead of `kherge/box`.

The `herrera-io/box` package is the actual library used by the Box application.

**Comment by lyrixx** [comment]
Ok. sorry.

**Comment by ghost** [comment]
It's okay!

If you do end up using `herrera-io/box`, let me know if you need help.
