### ISSUE TITLE
Wrong Compression info displayed

### ISSUE THREAD

**Issue by llaville** [box-project/box2#73]
With the info command, and my phar [1] built with this config file [2], i'm expected to see 

```
API Version: 1.1.0

Compression: GZ

Signature: SHA-1

Signature Hash: 7340905829AB998F922CF9AC5AE98C07332BEFB1
```

But I got

```
API Version: 1.1.0

Compression: None

Signature: SHA-1

Signature Hash: 7340905829AB998F922CF9AC5AE98C07332BEFB1
```

[1] http://bartlett.laurent-laville.org/get/phpreflect.phar
[2] https://github.com/llaville/php-reflect/blob/v2/box.json

**Comment by llaville** [comment]
It's strange ! Issue seems not came from info command.

I use this test script to verify after building process

``` php
<?php

$fn = '/var/pirum/servers/bartlett/get/phpreflect.phar';  // 328 kb
$fn = '/home/github/php-reflect/phpreflect.phar';         // 883 kb

$p = new Phar($fn, 0);

var_dump($p->getSupportedCompression());
var_dump($p->isCompressed());
```

The phar file I've uploaded is 328 kb size , when I used the "compression": "GZ" option

And the 883kb is without this option.
But in both case the test script gave me the same result : 

```
array(1) {
  [0]=>
  string(2) "GZ"
}
bool(false)
```

The phar seems well compressed, but the Phar class tell me, as Box 2.4.3 that the file is not compressed.

Possible issue with Phar

**Comment by ghost** [comment]
I think there might be a misunderstanding of how compression works with phars. There are two kinds:
- [Phar::compress](http://us2.php.net/manual/en/phar.compress.php) — Compresses **the entire Phar archive** using Gzip or Bzip2 compression
- [Phar::compressFiles](http://us2.php.net/manual/en/phar.compressfiles.php) — Compresses **all files in the current Phar** archive

Box uses `Phar::compressFile()`, which will not show up as compressed with the `info` command. This is because the individual files in the archive are compressed, rather than the entire phar file. The `Phar::isCompressed()` method is used by Box to determine if the entire phar file is compressed.
- [Phar::isCompressed](http://us2.php.net/manual/en/phar.iscompressed.php) — Returns Phar::GZ or PHAR::BZ2 if the **entire phar archive** is compressed (.tar.gz/tar.bz and so on)

It would probably benefit people if the `info` command also showed if one or more files are compressed within the phar file.

**Comment by llaville** [comment]
Thanks for your response :)
