### ISSUE TITLE
Fails to download manifest when used behind a corporate proxy

### ISSUE THREAD

**Issue by amercier** [box-project/box2#79]
Hello,

I encounter the following issue when installing Box from behind a corporate proxy:

```
Box Installer
=============

Environment Check
-----------------

"-" indicates success.
"*" indicates error.

 - You have a supported version of PHP (>= 5.3.3).
 - You have the "phar" extension installed.
 - You have a supported version of the "phar" extension.
 - You have the "openssl" extension installed.
 - The "phar.readonly" setting is off.
 - The "detect_unicode" setting is off.
 - The "allow_url_fopen" setting is on.
 - The "apc.enable_cli" setting is off.

Everything seems good!

Download
--------

 - Downloading manifest...


Error: file_get_contents(http://box-project.org/manifest.json): failed to open stream: Connection timed out

```

**Note:** my env vars (`http_proxy`, `https_proxy` and `ftp_proxy`) are setup correctly. I can `curl http://box-project.org/manifest.json`.

**Comment by ghost** [comment]
Unfortunately this isn't something I can fix at the moment, but it should not a problem anymore with the new release of Box (3.0) that I'm working on since it'll be using cURL.

For the meantime, however, you can download Box from the [releases page](https://github.com/kherge/php-box/releases). Because of the proxy issue, it might also mean that you will need to manually download any updates that are released from the release page as well.

**Comment by amercier** [comment]
OK thanks, looking forward to v3.0.
